In [1]:
import cv2
import numpy as np

In [2]:
img = cv2.imread('image/car.jpg')
print(img)

[[[227 227 227]
  [235 235 235]
  [236 236 236]
  ...
  [237 237 237]
  [236 236 236]
  [228 228 228]]

 [[250 250 250]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [249 249 249]]

 [[247 247 247]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [254 254 254]
  [246 246 246]]

 ...

 [[247 247 247]
  [255 255 255]
  [255 255 255]
  ...
  [253 253 253]
  [255 255 255]
  [246 246 246]]

 [[247 247 247]
  [255 255 255]
  [255 255 255]
  ...
  [253 253 253]
  [255 255 255]
  [246 246 246]]

 [[247 247 247]
  [255 255 255]
  [255 255 255]
  ...
  [253 253 253]
  [255 255 255]
  [246 246 246]]]


In [3]:
img = cv2.imread('image/imge.jpg')
cv2.imshow("Mohamed", img)
cv2.waitKey(0)

-1

In [ ]:
new_width = 500  
new_height = 300 
resized_image = cv2.resize(img, (new_width, new_height))


In [ ]:
cv2.imwrite('output_image.jpg', resized_image)


True

## Open Camera

In [4]:
cam = cv2.VideoCapture(0)
while True:
    ret , frame = cam.read()
    cv2.imshow('Mhamed',frame)
    if cv2.waitKey(1) & 0xff == ord('q') :               
        break

cam.release()
cv2.destroyAllWindows()    