In [1]:
import cv2 
import numpy as np

In [2]:
image = cv2.imread('image/car.jpg')
print(image)

[[[227 227 227]
  [235 235 235]
  [236 236 236]
  ...
  [237 237 237]
  [236 236 236]
  [228 228 228]]

 [[250 250 250]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [249 249 249]]

 [[247 247 247]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [254 254 254]
  [246 246 246]]

 ...

 [[247 247 247]
  [255 255 255]
  [255 255 255]
  ...
  [253 253 253]
  [255 255 255]
  [246 246 246]]

 [[247 247 247]
  [255 255 255]
  [255 255 255]
  ...
  [253 253 253]
  [255 255 255]
  [246 246 246]]

 [[247 247 247]
  [255 255 255]
  [255 255 255]
  ...
  [253 253 253]
  [255 255 255]
  [246 246 246]]]


In [4]:
cv2.imshow('Frame',image)
cv2.waitKey(0)

-1

## Brightness Increase

In [3]:
brightness_increase = 50
brightened_image = np.uint8(np.clip(image + brightness_increase, 0, 255))

cv2.imwrite('brightened_image.jpg', brightened_image)


True

## Brightness Decresse

In [4]:
brightness_decrease = 50
brightness_image2 = np.uint8(np.clip(image - brightness_decrease, 0, 255))

cv2.imwrite('brightness_image2.jpg', brightness_image2)


True